### PR TITLE
Make fpath configureable

### PR DESCRIPTION
**Pull request by Tarrasch**
This patch set contains some small minor re-factorings, but most changes are in the second last commit.

Please review @blueyed, at least the test files `Compdef.hs` and `compdef.t`. Hey by the way,  have you tried out antigen-hs, do you like it? :)

### CODE REVIEW

**Comment by Tarrasch** [comment]
ping @blueyed

**Comment by Tarrasch** [comment]
You can still audit if you want :)

**Comment by blueyed** [comment]
Heh.. :)

I don't think I can help much with reviewing, and no, I am not using antigen-hs (nor antigen) currently/yet.

**Comment by Tarrasch** [comment]
That's cool. Thanks for replying :)

**Pull request merged**
