### PR TITLE
Drop shelly dependency.

### PR DESCRIPTION
**Pull request by abhinav**
This commit drops the dependency of antigen-hs on shelly, allowing a much
simpler installation story. The package will now build with just the standard
GHC packages + text, and text is probably already installed globally because
cabal-install needs it. This also drops the dependency on the deprecated
system-filepath package.

I also changed the behavior of Development RepoStorage. I renamed it to Local,
and the behavior is basically: things inside a Local RepoStorage will be
sourced as-is, without copying over to ~/.antigen-hs. You still have to run
antigen-hs-compile to start sourcing anything new that was added to a Local
RepoStorage.

---

If you did not want to drop that dependency, feel free to close this PR. I made the change mostly so that I could use it without installing shelly and friends globally.

### CODE REVIEW

**Comment by Tarrasch** [comment]
I very much welcome this patch! To drop the Shelly dependency would be awesome. I initially didn't want it because of the hassle, but it just became *so* much more convenient with it. But since you've implemented this now, I'm happy to merge.

But there to be some build failures, if you could fix those, I'll be super happy to merge. :)

**Comment by abhinav** [comment]
That's weird. cram failed to match the glob. Seems to work just fine otherwise.

**Comment by abhinav** [comment]
Oh. Trailing slash in the example.

**Comment by Tarrasch** [comment]
So can this be merged now you think?

**Comment by abhinav** [comment]
Oh yeah, I should've added that. Yup, it's ready to merge.

**Comment by abhinav** [comment]
There was a change in how you instantiate the Config. I updated the README with that. 

Instead of

    AntigenConfiguration bundles

You do,

    defaultConfig { plugins = bundles }

**Comment by Tarrasch** [comment]
Yea, it was totally a mistake from my side to not apply the "default value pattern" on the antigen configuration.

**Comment by Tarrasch** [comment]
Thanks @abhinav !!

**Comment by onemanstartup** [comment]
So it depends on Shelly or not?
In readme it said that you need install shelly.
Also with defaultConfig I get 
```
/Users/onemanstartup/.zsh/antigen-hs/../MyAntigen.hs:54:10:
    Not in scope: ‘defaultConfig’
```

**Comment by abhinav** [comment]
Oh, the instructions should probably be updated in the README to not ask for shelly. Created PR #22. It drops the `cabal install shelly` from the instructions.

**Comment by onemanstartup** [comment]
https://github.com/onemanstartup/antigen-hs/pull/1 lol I created pull request to fork :laughing: 
@abhinav you forgot to add import statement with defaultConfig

**Comment by abhinav** [comment]
Oh, hah. Good catch. Updated PR.

**Pull request merged**
